### ISSUE TITLE
Problems creating a pool where www-data isn't the user/group

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-php#13]
Been running into issues trying to create pools where the user and group isn't `www-data`. When you use `debops.php` as a dependency, the pools get created and php-fpm restarted before I get a chance to create a user. I'm not sure how to work around it. 

Should I use `debops.users` to create it? What would it look like? Would this work?

``` yml
php_user:
    name: 'php-fpm' 
    state: 'present'
    group: 'php-fpm'
    systemuser: True
    systemgroup:  True
```

**Comment by carlalexander** [comment]
Just ran some tests and it seems to run fine. Just want to confirm this is the correct way to configure a system user.

**Comment by drybjed** [comment]
The `debops.php` role (and some others as well), can create users and groups just for situations like this. There's [a set of tasks](https://github.com/debops/ansible-php/blob/master/tasks/main.yml#L152-L181) which will make sure that the groups and users exist. All you need to do is specify additional keys in the pool definition:

``` yaml
php__dependent_pools:
  - name: 'application-pool'
    owner: 'application-user'
    group: 'application-group'
    home: '/srv/application-home'
    system: True     # use UID/GID < 1000
```

The accounts created by `debops.php` are bare bones. You are supposed to configure the rest of the user account (GECOS, shell, etc.) in your own role.
