### ISSUE TITLE
Allow for different configs for CLI/fpm/etc

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-php#28]
This is a bit of tricky issue. I noticed this with the memory limit of PHP CLI. It should be `-1` to work with command line clients like composer. But, right now, `00-ansible.ini` gets synced to both `cli` and `fpm` with the value from `php__ini_memory_limit`.

`128M` is more than enough for fpm, but it's not always enough for CLI. Same with execution time. You might want longer execution times for CLI than fpm.

Is there a way to create a configuration for file for just CLI or just fpm?

**Comment by drybjed** [comment]
That should be possible. Can you check if setting:
```
[CGI]
cgi.fix_pathinfo = 0
memory_limit = -1
```
solves the issue with `php-cgi`?

**Comment by carlalexander** [comment]
I'll try it out and let you know!

**Comment by carlalexander** [comment]
Yep, that worked! I'll make PR to add it.

**Comment by carlalexander** [comment]
Actually, this made the memory limit `-1` for FPM too. So back to the drawing board. Is there a way to create an ini file that applies only to `/etc/php/7.0/cli/conf.d`?

**Comment by drybjed** [comment]
Sure, with something like this in the inventory (can be added in the role as well):
```yaml
php__host_configuration:
  - filename: '../cli/conf.d/30-memory_limit'
    name: 'PHP'
    options: |
      ; Don't limit memory for php-cli execution
      memory_limit = -1
```
